### ISSUE TITLE
Retention

### ISSUE THREAD

**Issue by fire** [timescale/prometheus-postgresql-adapter#14]
How do you drop chunks to reduce storage?

**Comment by syepes** [comment]
Should be something like: `SELECT drop_chunks(interval '12 months', 'metrics_values');`

**Comment by fire** [comment]
Can you add this to the documentation? Thanks!

**Comment by martinseener** [comment]
Hi,
we use this with PostgreSQL 10.1 and without TImescaleDB, so plain PG. We're unable to define retention times so our DB grows and grows.
When i switch to the prometheus DB in postgres there is also no way to manually remove data, because there are no relations. The command above also doesn't work.

Do you have any ideas, what we can do in order to have a 7d retention time somehow?

Thanks for any help!

**Comment by martinseener** [comment]
Here is our current systemd config for prometheus but i'm unsure if prometheus will remove data older than 7d. not sure if tsdb retention works for PG.

`ExecStart=/usr/local/bin/prometheus \
  --config.file=/etc/prometheus/prometheus.yaml \
  --storage.tsdb.path=/var/lib/prometheus \
  --storage.tsdb.retention=7d \
  --web.console.templates=/usr/local/share/prometheus/consoles \
  --web.console.libraries=/usr/local/share/prometheus/console_libraries \
  --web.external-url=https://prometheus.example.com/prometheus \
  --web.listen-address="127.0.0.1:9090"`

**Comment by niksajakovljevic** [comment]
Hi @martinseener, Prometheus retention and TimescaleDB retention is configured/managed separately. If you want to remove all the metrics data older than 7 days you can run:

`SELECT drop_chunks(interval '7 days', 'metrics_values');`

You might want the above command to run regularly inside some scheduler... 

Note that above SQL command only works if you use PostgreSQL with TimescaleDB ( which you probably should in order to get better read/write performances and other optimizations)

**Comment by martinseener** [comment]
Hi @niksajakovljevic 
sadly we're currently dont use the timescaleDB extension, so we probably have a problem. Is there no other way? Can this also not be added in the adapter without timescaledb?
Thanks for help!

**Comment by niksajakovljevic** [comment]
@martinseener Installing TimescaleDB extension is a matter of running few commands (https://docs.timescale.com/v0.12/getting-started) so I highly recommend that. Anyways it's your call. This will not be supported from the adapter.

**Comment by martinseener** [comment]
Hi, lots of thx for helping! Sadly we currently use 10.1 (and its needed to have 10.2) and we're using a HA Patroni PG Cluster and restarting nodes is possible but not so easily doable. So we currently have at least one major showstopper from using timescaleDB with postgres.

**Comment by mfreed** [comment]
Hi @martinseener:  So Postgres core accidentally made some breaking changes between 10.1 and 10.2 that led to ABI incompatibilities (e.g., how they layout memory for column metadata).  

This was unfortunate but beyond our control; it's hard to always prevent these things from sneaking in for such a large and active project.  And in fact, it was our users that actually first identified this problem, and because of it we actually run daily smoke tests against Postgres development master to check for various ABI issues like this.  But because of that, any binaries that we build (against 10.2+) are incompatible with 10.1, so we dropped support of it.

Note that you *can* build TimescaleDB from source for 10.1 yourself, but if you ever do upgrade to 10.2+, you'll have to similarly upgrade TimescaleDB at the same time.  In general, we would recommend upgrading to something like a later version of PG10, but that's obviously your call.  Cheers!
